### ISSUE TITLE
how best to synchronize library version

### ISSUE THREAD

**Issue by mingness** [mingness/processing-library-template#13]
the library needs to report it's version, so the version needs to be in the java code, but it is also a part of the gradle build parameters. How best to synchronized these values - to manually update is prone to human error.

1. Check if the gradle build requires the version
2. if so, check if there is a way to read in gradle properties into java, or java variables into gradle.

**Comment by mingness** [comment]
I checked where the `version` parameter in Gradle was used. It's main use is when publishing to Maven, which we don't do at the moment. Otherwise, it's used in the <head><title> of the javadocs, so it's lack is not obvious for our uses. 

So it's really at the moment about synchronizing the version in the code, and in the library.properties file. Maybe, we can read in the version from a gradle properties file? That is related to another issue.

Just to be complete, I found another pattern was to store the version in a separate text file, and read it into either Java and gradle. I don't love this.

**Comment by mingness** [comment]
Hmm, it just occurred to me, that if we design the library to use a java function that reads the version from a text file, then that text file would have to be there for the function to run. Looks like the libraries.properties file is copied into the library folder, but it does make the jar brittle, to be dependent on the presence of that file. I guess then, the better option is to see if we can get the value in the Java file into the library.properties file, probably through Gradle?

**Comment by enkatsu** [comment]
@mingness 
After hearing your opinion, I've come to the same conclusion. In this case, we need to ensure that a class containing the library version information definitely exists. If we want to maintain flexibility in library development, I think it might be a good idea to prepare a separate class like `LibraryProperty.java` or `Version.java`.

**Comment by mingness** [comment]
Can you describe more your vision for the Version.java class? thanks.

**Comment by enkatsu** [comment]
@mingness 
When Gradle retrieves the version from Java code, I think there needs to be a fixed class that holds the VERSION variable. However, libraries don't necessarily always have a single main class. A good example of a library composed of multiple classes with similar treatment might be HTTP-Requests-for-Processing. In this case, I think GetRequest.java and PostRequest.java are treated equivalently.
Therefore, when using this template, we might need to establish a convention that there exists a class for managing meta-information such as the library version.

**Comment by mingness** [comment]
@enkatsu I see your reasoning. So the question is, is having a version class in java more intuitive than the string-search-and-replace-via-Gradle method currently employed in the processing template. I think the version class is worth a quick test of what it could look like and how it would integrate in both ways of structuring a library, with a single main class, or the multiple classes.

**Comment by enkatsu** [comment]
@mingness Thank you for understanding. I also think it's worth testing. I was able to read the version from compiled Java code using a Gradle script like the one below. I hope this helps 🙏 

```kts
buildscript {
    dependencies {
      classpath(files("release/mylibrary/library/mylibrary.jar"))
   }
}

tasks.register("writeVersionTest") {
   println(com.example.mylibrary.Version.VERSION)
}
```

**Comment by mingness** [comment]
So, I'm wondering, how necessary it is to return the version from the java application. The contributions manager returns what version is installed, and this is taken from the library.properties file. The processing/processing-library-template, which was built with ant, did configure the application to return the version, which gives the impression that this is necessary. Yet, who uses it? I looked through the github wiki about contributing libraries, and saw no mention of the requirement to return the version from the library itself. So, I might have been mistaken about this task. @Stefterv @SableRaf can I remove this issue, and remove mention of the version from the java code itself? I have seen already, a more recent library that didn't return the version, which is listed in the contributions. Thanks @enkatsu for thinking about this issue.

**Comment by Stefterv** [comment]
I think it is sometimes used to check if you have the right version of a library installed by e.g. `println(Library.VERSION);` I think for the target audience that this template is aimed at, I would not call it top priority.

**Comment by Stefterv** [comment]
Especially looking at previous implementations of how this was done before, I don't like the coupling and complexity for a function that is rarely used

**Comment by mingness** [comment]
Thanks for your feedback.
