### ISSUE TITLE
Does a new library need to be backwards compatible?

### ISSUE THREAD

**Issue by mingness** [mingness/processing-library-template#28]
As I understand, Processing 4 was built with Java 17.
Previous templates declare a sourceCompatibility of Java 8.
The current template is using the recommended toolchain to define Java 17, which automatically sets the source and target compatibility to the same version.

**Comment by SableRaf** [comment]
It's ok to make this template compatible with Processing 4 and newer versions. The instructions and tools for creating libraries for Processing 3 and earlier will still available for anyone who needs them.

**Comment by mingness** [comment]
Thanks! I'll close this issue then.
