### ISSUE TITLE
Release through GitHub

### ISSUE THREAD

**Issue by Stefterv** [mingness/processing-library-template#30]
Hey all looks great!

Can I also suggest that we add instructions how to do releases through Github / Github desktop in addition to what has been done in #25, I think the git command line is somewhat opaque for beginners and often results in accidental actions.

**Comment by enkatsu** [comment]
@Stefterv Hello.
I completely agree with you. This GitHub Actions workflow is triggered by pushing a Git tag, so I think we could write instructions on how to add and push a tag through GitHub Desktop. Would that kind of content be appropriate?

**Comment by Stefterv** [comment]
Yes, I'm also curious if the system works with creating a new release on the site

**Comment by SableRaf** [comment]
> I'm also curious if the system works with creating a new release on the site

Same here. Currently, the script which updates the Contributions Manager (CM) looks for a release tagged `latest`. 

We can think of updating the intake on the CM side but it's probably best to start by building around the current pipeline.

**Comment by Stefterv** [comment]
Ah it was always creating a release on the site, this is just talk about what is triggering a new release

**Comment by mingness** [comment]
This issue has been address in #41 .
